# Generated by Django 6.0.4 on 2026-04-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Button text/label (e.g., 'View Diagram')", max_length=100)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_media/images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='article_media/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='article_media/video/')),
                ('youtube_url', models.URLField(blank=True, help_text='Provide standard YouTube URL', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='articles.article')),
            ],
            options={
                'verbose_name_plural': 'Article Media',
                'ordering': ['order'],
            },
        ),
    ]
