# Generated by Django 6.0.4 on 2026-04-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemedia',
            name='media_type',
        ),
    ]
