# Generated by Django 6.0.4 on 2026-04-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_subsubcategory'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubSubCategory',
        ),
    ]
