# Generated by Django 6.0.4 on 2026-04-13 00:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_subsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
