# Generated by Django 6.0.4 on 2026-04-13 00:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_body_alter_articlesection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
