# Generated by Django 6.0.4 on 2026-04-12 11:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='The word/phrase to highlight', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('explanation', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='glossary/images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='glossary/audio/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTermMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_index', models.PositiveIntegerField(default=0, help_text='0 means highlight all occurrences, 1 means first, etc.')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_mappings', to='articles.article')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_mappings', to='glossary.interactiveterm')),
            ],
            options={
                'unique_together': {('article', 'term', 'occurrence_index')},
            },
        ),
    ]
