# Generated by Django 6.0.4 on 2026-04-13 07:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveterm',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text only (🔍)'), ('image', 'Image + Text (🖼️)'), ('audio', 'Audio + Text (🔊)'), ('video', 'Video + Text (🎥)')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='interactiveterm',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='glossary/video/'),
        ),
        migrations.AddField(
            model_name='interactiveterm',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL', null=True),
        ),
        migrations.AlterField(
            model_name='interactiveterm',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interactiveterm',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True),
        ),
    ]
