# Generated by Django 6.0.4 on 2026-04-13 00:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiveterm',
            name='explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
