# Generated by Django 6.0.4 on 2026-04-13 00:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_alter_interactiveterm_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiveterm',
            name='explanation',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
